language: c
dist: bionic
compiler:
  - gcc

addons:
  apt:
    sources:
      - sourceline: "ppa:team-gcc-arm-embedded/ppa"
    packages:
      - python3
      - ruby
      - gcc-arm-embedded

install:
  - gem install ceedling

before_script:
  - wget http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports/msp430-gcc-8.2.0.52_linux64.tar.bz2 -O /tmp/msp430-gcc.tar.b2
  - tar -xjf /tmp/msp430-gcc.tar.b2
  - export PATH=$PATH:$PWD/msp430-gcc-8.2.0.52_linux64/bin
  - arm-none-eabi-gcc --version
  - msp430-elf-gcc --version

script:
  # Build all examples
  - python3 tools/build_all.py
  # Run unit tests
  - cd test
  - ceedling test:all
  - cd ..

after_success:
  - source tools/build_success.sh
