name: TinyUSB CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Setup Ruby
      uses: actions/setup-ruby@v1.0.0
    - name: Install Toolchains
      run: |
        # Install XPM
        npm install --global xpm
        # Install ARM GCC
        xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@latest
        export PATH=$PATH:`echo $HOME/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/*/.content/bin`
        # Install RISCV GCC
        xpm install --global @xpack-dev-tools/riscv-none-embed-gcc@latest
        export PATH=$PATH:`echo $HOME/opt/xPacks/@xpack-dev-tools/riscv-none-embed-gcc/*/.content/bin`
        arm-none-eabi-gcc --version
        riscv-none-embed-gcc --version
    - name: Git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Unit Tests
      run: |
        # Install Ceedling
        gem install ceedling
        cd test
        ceedling test:all
        cd ..
    - name: Build
      run: |
        python3 tools/build_all.py board_test
