name: TinyUSB CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Node.js
      uses: actions/setup-node@v1.1.0
    - name: Toolchains
      run: |
        # Install XPM
        npm install --global xpm
        xpm install --global @xpack-dev-tools/riscv-none-embed-gcc@latest
        export PATH=$PATH:`$HOME/opt/xPacks/@xpack-dev-tools/riscv-none-embed-gcc/*/.content/bin`
        # sudo apt-get install -y gettext
        # pip install requests sh click setuptools awscli
        # wget https://adafruit-circuit-python.s3.amazonaws.com/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        # sudo tar -C /usr --strip-components=1 -xaf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
    - name: Versions
      run: |
        #arm-none-eabi-gcc --version
        riscv-none-embed-gcc --version
    - name: Git clone
      uses: actions/checkout@v1
      with:
        submodules: true
