name: Hardware Test
on:
  workflow_dispatch:

# Hardware in the loop (HIL)
# Current self-hosted instance is running on an RPI4 with
# - pico + pico-probe connected via USB
# - pico-probe is /dev/ttyACM0

jobs:
  hw-test:
    # Limit the run to only hathach due to limited resource on RPI4
    #if: github.repository_owner == 'hathach' && ${{ github.event.workflow_run.conclusion == 'success' }}
    if: github.repository_owner == 'hathach'
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning up previous run"
        rm -rf "${{ github.workspace }}"
        mkdir -p "${{ github.workspace }}"
        
    - name: Download rp2040 Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build_arm.yml
        name: rp2040
        
    - name: Test cdc_dual_ports
      env:
        example: cdc_dual_ports
      run: |
        openocd -f "interface/picoprobe.cfg" -f "target/rp2040.cfg" -c "program ${{ env.example }}.elf verify reset exit"
        echo "Waiting for enumeration"
        while ! lsusb | grep "cafe:" ; do : ; done
        # Test
        test -e /dev/ttyACM1
        test -e /dev/ttyACM2

    - name: Test cdc_msc
      env:
        example: cdc_msc
      run: |
        openocd -f "interface/picoprobe.cfg" -f "target/rp2040.cfg" -c "program ${{ env.example }}.elf verify reset exit"
        echo "Waiting for enumeration"
        while ! lsusb | grep "cafe:" ; do : ; done
        # Test
        test -e /dev/ttyACM1
        test -e /media/pi/TinyUSB\ MSC/README.TXT
        cat /media/pi/TinyUSB\ MSC/README.TXT
