name: Hardware Test
on:
  workflow_dispatch:

# Hardware in the loop (HIL)
# Current self-hosted instance is running on an RPI4 with
# - pico + pico-probe connected via USB

jobs:
  hw-test:
    # Limit the run to only hathach due to limited resource on RPI4
    #if: github.repository_owner == 'hathach' && ${{ github.event.workflow_run.conclusion == 'success' }}
    if: github.repository_owner == 'hathach'
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Test self-host
      run: |
        echo "Running on self-hosted"
        ls
        
    - name: Download rp2040 Artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build_arm.yml
        name: rp2040
        
    - name: List
      run: ls

#    - name: Clean workspace
#      run: |
#        echo "Cleaning up previous run"
#        rm -rf "${{ github.workspace }}"
#        mkdir -p "${{ github.workspace }}"

    